

- name: "Update Apt Cache"
  apt: 
    update_cache: yes
  tags: installation

- name: "Install Common packages"
  apt:
    name: ['runc', 'python-pip', 'docker.io', 'python3-venv', 'docker-compose']
    state: latest
  tags: installation, packages

- name: "Python Docker"
  pip:
    name: 
      - docker
  tags: python

- name: "Install Minikube"
  shell: 
    cmd: curl -Lo ~/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm && chmod +x ~/minikube && mkdir -p /usr/local/bin/ && install ~/minikube /usr/local/bin/
  tags: installation, minikube